Efk improvements (#6)
* NEW: efk/ - Files to initialize Elasticsearch added.
* NEW: efk/ - Files to initialize Kibana added.
* FIX: Typos in README.md
* CHG: */data folders moved to /data
* CHG: Initialization with git-sync removed

diff --git a/efk/elasticsearch.yaml b/efk/elasticsearch.yaml
--- a/efk/elasticsearch.yaml
+++ b/efk/elasticsearch.yaml
@@ -17,8 +17,65 @@ spec:
     spec:
       containers:
       - name: elasticsearch
-        image: docker.elastic.co/elasticsearch/elasticsearch:7.9.0
+        image: docker.elastic.co/elasticsearch/elasticsearch:7.6.2
         imagePullPolicy: IfNotPresent
+        lifecycle:
+          postStart:
+            exec:
+              command:
+              - bash
+              - "-c"
+              - |
+                set -x
+
+                cd /var/tmp/elasticsearch-init/
+
+                ES_HOST=localhost
+                ES_PORT=9200
+                DATE=$(date +%Y.%m.%d)
+                
+                requests=0
+                max_requests=30
+                sleep_for=5
+
+                while true; do
+                  STATUS_CODE=$(curl -s -m 10 -k -L -o /dev/null -w "%{http_code}" "http://${ES_HOST}:${ES_PORT}")
+                  requests=$((requests+1))
+                  echo "INFO: Request Nr. " $requests
+                  if [ "${STATUS_CODE}" = "200" ]; then
+                	  echo "INFO: Elasticsearch is started."
+                	  break
+                  fi
+                  if [ ${requests} -gt ${max_requests} ]; then
+                	  echo "FAILED: Instance not ready in time."
+                	  echo " # timeout"
+                	  exit 1
+                  fi
+                  sleep ${sleep_for}
+                done
+
+                function curl_es() {
+                	curl -fisS -w '\n' \
+                		-X "${1}" \
+                		${3:+-H 'Content-Type: application/json' -d "@$3"} \
+                		"http://${ES_HOST}:${ES_PORT}${2}"
+                }
+
+                curl_es 'PUT' '/_template/default' './default-template.json'
+              
+                if ((NO_IAM != 1)); then
+                  curl_es 'PUT' '/_ingest/pipeline/airlock-iam-default-pipeline' './airlock-iam-ingest-pipeline.json'
+                  curl_es 'PUT' '/_template/airlock-iam' './airlock-iam-template.json'
+                  curl_es 'PUT' '/_template/airlock-iam' './airlock-iam-settings.json'
+                fi
+                
+                if ((NO_WAF != 1)); then
+                  curl_es 'PUT' '/_ingest/pipeline/airlock-waf-default-pipeline' './airlock-waf-ingest-pipeline.json'
+                  curl_es 'PUT' '/_template/airlock-waf' './airlock-waf-template.json'
+                  curl_es 'PUT' '/_template/airlock-waf' './airlock-waf-settings.json'
+                fi
+                
+                echo -e "\n\e[0;32mElasticsearch setup completed\e[0m\n"
         env:
         - name: TZ
           valueFrom:
@@ -34,11 +91,17 @@ spec:
           containerPort: 9300
         volumeMounts:
         - name: data
+          mountPath: /var/tmp/elasticsearch-init/
+          subPath: elasticsearch
+        - name: elasticsearch-data
           mountPath: "/usr/share/elasticsearch/data"
       volumes:
       - name: data
         persistentVolumeClaim:
-          claimName: elasticsearch-pv-claim
+          claimName: data-claim
+      - name: elasticsearch-data
+        persistentVolumeClaim:
+          claimName: elasticsearch-claim
 ---
 apiVersion: v1
 kind: Service
@@ -58,7 +121,7 @@ spec:
 apiVersion: v1
 kind: PersistentVolumeClaim
 metadata:
-  name: elasticsearch-pv-claim
+  name: elasticsearch-claim
 spec:
   accessModes:
   - ReadWriteOnce
diff --git a/efk/kibana.yaml b/efk/kibana.yaml
--- a/efk/kibana.yaml
+++ b/efk/kibana.yaml
@@ -17,8 +17,71 @@ spec:
     spec:
       containers:
       - name: kibana
-        image: docker.elastic.co/kibana/kibana:7.9.0
+        image: docker.elastic.co/kibana/kibana:7.6.2
         imagePullPolicy: IfNotPresent
+        lifecycle:
+          postStart:
+            exec:
+              command:
+              - bash
+              - "-c"
+              - |
+                set -x
+
+                cd /var/tmp/kibana-init/
+
+                KIBANA_HOST=localhost
+                KIBANA_PORT=5601
+
+                requests=0
+                max_requests=30
+                sleep_for=5
+
+                while true; do
+                  STATUS_CODE=$(curl -s -m 10 -k -L -o /dev/null -w "%{http_code}" "http://${KIBANA_HOST}:${KIBANA_PORT}${SERVER_BASEPATH}/api/status")
+                  requests=$((requests+1))
+                  echo "INFO: Request Nr. " $requests
+                  if [ "${STATUS_CODE}" = "200" ]; then
+                	  echo "INFO: Kibana is started."
+                	  break
+                  fi
+                  if [ ${requests} -gt ${max_requests} ]; then
+                	  echo "FAILED: Instance not ready in time."
+                	  echo " # timeout"
+                	  exit 1
+                  fi
+                  sleep ${sleep_for}
+                done
+
+                function kibana_index_patterns() {
+                  curl -fsS -w '\n' \
+                    -X 'POST' \
+                    -H 'kbn-xsrf: true' -H 'Content-Type: application/json' \
+                    -d "@$1" \
+                    http://"${KIBANA_HOST}:${KIBANA_PORT}${SERVER_BASEPATH}/api/saved_objects/_bulk_create?overwrite=true"
+                }
+
+                function kibana_import() {
+                  curl -fsS -w '\n' \
+                    -X POST \
+                    -H 'kbn-xsrf: true' \
+                    --form "file=@$1" \
+                    http://"${KIBANA_HOST}:${KIBANA_PORT}${SERVER_BASEPATH}/api/saved_objects/_import?overwrite=true"
+                }
+
+                kibana_index_patterns './default-index-patterns.json'
+                
+                if ((NO_IAM != 1)); then
+                	kibana_index_patterns './airlock-iam-index-patterns.json'
+                	kibana_import './airlock-iam-kibana.ndjson'
+                fi
+                
+                if ((NO_WAF != 1)); then
+                	kibana_index_patterns './airlock-waf-index-patterns.json'
+                	kibana_import './airlock-waf-kibana.ndjson'
+                fi
+
+                echo -e '\n\e[0;32mKibana setup completed\e[0m\n'
         env:
         - name: TZ
           valueFrom:
@@ -34,6 +97,14 @@ spec:
         ports:
         - containerPort: 5601
           name: webinterface
+        volumeMounts:
+        - name: data
+          mountPath: /var/tmp/kibana-init/
+          subPath: kibana
+      volumes:
+      - name: data
+        persistentVolumeClaim:
+          claimName: data-claim
 ---
 apiVersion: v1
 kind: Service
